### ISSUE TITLE
Custom Attribute Set issues

### ISSUE THREAD

**Issue by matdave** [buric/Inchoo_FeaturedProducts#12]
I can't seem to "Feature" products that have a custom attribute set.

**Comment by buric** [comment]
Hello @matdave,

did you add the 'is_featured' attribute to that set?

Regards

**Comment by matdave** [comment]
Do you mean "inchoo_featured_product"? If so, then yes that is assigned to all attribute sets.

**Comment by matdave** [comment]
I looked threw your code, and noticed we had just a weird setup that was causing issues.  Visibility was set to "Search", and the Featured Products grid checked against that.
