### ISSUE TITLE
can't find template

### ISSUE THREAD

**Issue by igabc** [buric/Inchoo_FeaturedProducts#23]
"If you use custom theme you'll need to copy template and layout files from app/design/frontend/default/default to app/design/frontend/your_package/your/theme in order to see anything on frontend"

I just downloaded the files. I don't have the "app/design/frontend/default" in the package.
I have only rwd and base inside the "frontend" dir.

I have set this featured products block in home page, which is set to 1 column. the products list is on 3 columns only. I guess the missing default template files have something to do with this.
thanks

**Comment by buric** [comment]
How do you mean? The files are in base/default folder...

**Comment by igabc** [comment]
"If you use custom theme you'll need to copy template and layout files from app/design/frontend/default/default"

then change what you wrote to:
"If you use custom theme you'll need to copy template and layout files from app/design/frontend/**base**/default..."

:)

**Comment by buric** [comment]
There is no need to move any files from the base/default theme as it's Magento's standard fallback.

**Comment by igabc** [comment]
You don't understand...

"If you use custom theme you'll need to copy template and layout files from app/design/frontend/default/default to app/design/frontend/your_package/your/theme in order to see anything on frontend"

This is wrong. You need to change the text to

"If you use custom theme you'll need to copy template and layout files from app/design/frontend/**base**/default to app/design/frontend/your_package/your/theme in order to see anything on frontend"

because the files are in the BASE dir, not in the DEFAULT
